### ISSUE TITLE
[Question]<ESP32S3 can not build success>

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP3D-TFT#17]
I tried compiling the ESP32S3 board, for example ESP32S3_ZX3D50CE02S_USRC_4832。
But it cannot be compiled successfully。Due to USB SERIAL compilation not passing
Can you compile successfully？

**Comment by luc-github** [comment]
@liqijian101  Did you soilved your issue ?

**Comment by liqijian101** [comment]
My problem has been resolved because exceptions were not enabled
![屏幕截图 2023-07-16 104306](https://github.com/luc-github/ESP3D-TFT/assets/16173343/dddd63bc-273a-440c-a197-5a40cc8a468d)

**Comment by liqijian101** [comment]
But my screen is not displaying properly yet.I am testing.My screen is ST7796U, and I am using ESP32S3_ZX3D50CE02S_USRC_4832

**Comment by luc-github** [comment]
the default sdkconfig I provide has exception enabled - so yours may have been corrupted when changing target or doing anything 
about ESP32S3_ZX3D50CE02S_USRC_4832, it may be normal, I did not adjusted this resolution as mentionned here https://github.com/luc-github/ESP3D-TFT/discussions/6#discussioncomment-6398990 this resolution will be updated later

**Comment by luc-github** [comment]
I close issue then

**Comment by luc-github** [comment]
@liqijian101 I just flashed the ESP32S3_ZX3D50CE02S_USRC_4832 I have in hand and display is ok , controls are little bit small because is currently use the 240X320 resolution values for the dimentions but display is fine on my side and fully responsive, I just did some update today so you may need to refresh your fork

**Comment by liqijian101** [comment]
hi,luc
can you  know how to solve this problem?

ESP3D-TFT/main/modules/http/esp3d_http_service.cpp:228:41: error: 'const httpd_uri_t' {aka 'const httpd_ur
'} has no non-static data member named 'is_websocket'
  228 |         .supported_subprotocol = nullptr};

**Comment by luc-github** [comment]
No as I do not have it , and CI also pass - I need more context of what your are doing, and how you are compiling
