### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP3D-TFT#66]
After today's update, the following compilation errors occurred。

ESP3D-TFT/main/display/3dprinter/marlin/screens/main_screen.cpp:34:10: fatal error: files_screen.h: No such file or directory
   34 | #include "files_screen.h"

**Comment by luc-github** [comment]
Yes I have just fixed it now - it is due to file reorg and I did not modified enough files - I have updated all path

**Comment by liqijian101** [comment]
> Yes I have just fixed it now - it is due to file reorg and I did not modified enough files - I have updated all path

Can the updated program run normally.Now I  have a run error。

ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4200b75e
file: "./main/core/esp3d_tft.cpp" line 84
func: bool ESP3DTft::begin()
expression: bsp_init()

abort() was called at PC 0x40382cfb on core 0

**Comment by luc-github** [comment]
the bsp_init is hardware related - enable log to see what part is failing

**Comment by luc-github** [comment]
Additionnaly be sure only one hardware target is selected - currently the first target ON is selected , so it may compile for wrong target actually- I have just added a sanity check for this and for firmware selection to avoid such situation
