### ISSUE TITLE
I need help playing a GRBL file.

### ISSUE THREAD

**Issue by Mitko125** [luc-github/ESP3D-TFT#69]
I don't know if I should ask my question here and I apologize if I'm wrong.

I am unable to run "Play file" from SD card.
I am working with "ESP32_2432S028R" and "TARGET_FW_GRBL" in ESP3D-TFT.
I control the axles and other ....
But "Play file" does nothing. Example with json:
....
<Idle|MPos:1.000,0.000,1.000|FS:0,0|WCO:9.000,0.000,0.000>
ok
$J=G91 G21 X+1 F1000
ok
<Idle|MPos:2.000,0.000,1.000|FS:0,0|Ov:100,100,100>
ok
[ESP700]/SD/F200.nc json
{
 "cmd": "700",
 "status": "ok",
 "data": "ok"
}
<Idle|MPos:2.000,0.000,1.000|FS:0,0>
ok
...

I ran the same board and with "Configurator for ESP3D 3.0", the result was similar:
...
<Idle|MPos:1.000,1.000,-3.000|FS:0,0|Ov:100,100,100>
$J=G91 G21 Z-1 F1000
ok
error: stream failed: 1
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
[ESP700]/SD/F200.nc json
{
 "cmd": "700",
 "status": "ok",
 "data": "ok"
}
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
error: stream failed: 1
<Idle|MPos:1.000,1.000,-4.000|FS:0,0>
...

The difference is in "error: stream failed: 1".

I have recorded the responses to the [ESP800], [ESP420] commands for both cases if needed.
The file "F200.nc" is correct and I run it through "Candle 1.1.17".

I would be very grateful if you could point me to where I am wrong.

**Comment by luc-github** [comment]
cnc/grbl is not yet supported on ESP3D-TFT, only Marlin
I am on it https://github.com/luc-github/ESP3D-TFT/discussions/32#discussioncomment-9242766

**Comment by Mitko125** [comment]
I am familiar with where the configurator is for.
I did the tests on ESP3D 3.0, the board was the same. It was just easier for me with the configurator.
I had no problem with the files and the commands too.
ESP3D 3.0 with GRBL performed better than ESP3D-TFT.
But "Play file" still didn't work?!?

**Comment by luc-github** [comment]
streaming in esp3d is ping pong streaming and should work 
if any issue open ticket in esp3d repository or esp3d-webui if it is only webui issue 
please  fill all requested information to let me reproduce issue

**Comment by Mitko125** [comment]
I think the problem is with esp3d because I tried with several index.html.gz files. For this problem I will open a dispute there. I will just focus on GRBL in esp3d, Thank you for the quick replies.
