### ISSUE TITLE
Unable to connect to AP mode

### ISSUE THREAD

**Issue by liqijian101** [luc-github/ESP3D-TFT#70]
When I first downloaded the program, ESP3D was in AP mode and I couldn't connect the module through 192.168.0.1

**Comment by luc-github** [comment]
What do you mean by `I couldn't connect the module through 192.168.0.1` ?

You cannot connect to AP ?
You are connected to esp3dtft and you cannot join webserver using 192.168.0.1 ?

**Comment by liqijian101** [comment]
> You are connected to esp3dtft and you cannot join webserver using 192.168.0.1 ?

Yes

**Comment by luc-github** [comment]
Ok let me check

**Comment by luc-github** [comment]
I was able to reproduce issue  - but not sure what the root cause it
The log seemed incomplet - no networkservice was logging - then I rewrite the _started status collection and now seems Ok per my tests - @liqijian101  can you have check  with latest git and let me know ? no need to enable log

**Comment by liqijian101** [comment]
It is Ok
Thanks

**Comment by luc-github** [comment]
Ok cool - I close issue then
